---
#- name: Install go-specific apt packages
#  sudo: true
#  apt: name={{ item }} state=latest
#  with_items:
#    - vim-gocomplete
- name: Download Golang binary distribution
  get_url:
      url=https://storage.googleapis.com/golang/{{ go_archive_file }}
      dest={{ home }}/{{ go_archive_file }}
- name: Create ~/opt folder
  file:
      path={{ home }}/opt
      state=directory
- name: Unpack the Go binary distribution
  unarchive:
      copy=no
      src={{ home }}/{{ go_archive_file }}
      dest={{ home }}/opt
      creates={{ home }}/opt/go
- name: Add go path settings in .bashrc_mods
  lineinfile: dest={{ home }}/.bashrc_mods line="{{ item }}" insertafter=EOF
  with_items:
    - 'export GOROOT={{ home }}{{ go_root }}'
    - 'export GOPATH={{ home }}{{ go_path }}'
    - 'export PATH={{ home }}{{ go_root }}/bin:$PATH'
    - 'export PATH={{ home }}{{ go_path }}/bin:$PATH'
- name: Create go code folder
  file:
    dest={{ home }}{{ go_path }}/src/github.com
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
- name: Install some nice go packages
  command: >
      go get -u {{ item }}
  environment:
      GOPATH: "{{ home }}{{ go_path }}"
      GOROOT: "{{ home }}{{ go_root }}"
      PATH: "{{ home }}{{ go_root }}/bin:{{ home }}{{ go_path }}/bin:/usr/bin:/bin"
  with_items:
      - github.com/nsf/gocode
      - bitbucket.org/gotamer/gowatch
