---
#- name: Install go-specific apt packages
#  sudo: true
#  apt: name={{ item }} state=latest
#  with_items:
#    - vim-gocomplete
- name: Download Golang binary distribution
  get_url:
      url=https://storage.googleapis.com/golang/{{ go_archive_file }}
      dest={{ document_root }}/{{ go_archive_file }}
- name: Create ~/opt folder
  file:
      path={{ document_root }}/g/opt
      state=directory
- name: Unpack the Go binary distribution
  unarchive:
      copy=no
      src={{ document_root }}/{{ go_archive_file }}
      dest={{ document_root }}/g/opt
      creates={{ document_root }}/g/opt/go
- name: Add go path settings in .bashrc_mods
  lineinfile: dest={{ document_root }}/g/.bashrc_mods line="{{ item }}" insertafter=EOF
  with_items:
    - 'export GOROOT={{ home }}{{ go_root }}'
    - 'export GOPATH={{ home }}{{ go_path }}'
    - 'export PATH={{ home }}{{ go_root }}/bin:$PATH'
    - 'export PATH={{ home }}{{ go_path }}/bin:$PATH'
- name: Create go code folder
  file:
    dest={{ home }}{{ go_path }}/src/github.com
    state=directory
    recurse=yes
    owner={{ user }}
    group={{ user }}
- name: Install some nice go packages
  command: >
      go get -u {{ item }}
  environment:
      GOPATH: "{{ home }}{{ go_path }}"
      GOROOT: "{{ home }}{{ go_root }}"
      PATH: "{{ home }}{{ go_root }}/bin:{{ home }}{{ go_path }}/bin:/usr/bin:/bin"
  with_items:
      - github.com/nsf/gocode
      - bitbucket.org/gotamer/gowatch
- name: Check out vim-go
  git:
    repo=https://github.com/fatih/vim-go.git
    dest={{ document_root }}/src/vim-go
    update=yes
- name: Ensure ~/.vim/bundle exists
  file:
    dest={{ document_root }}/.vim/bundle
    state=directory
- name: Symlink vim-go to .vim/bundle
  file:
    src={{ document_root }}/src/vim-go
    dest={{ document_root }}/.vim/bundle/vim-go
    state=link
# TODO: Add bitbucket.org/gotamer/gowatch for folder watching and running tests!
