---

- name: Add 3rd party repos
  apt_repository: repo='ppa:neovim-ppa/unstable'

- name: Update repository cache
  action: apt update_cache=yes
  sudo: yes

- name: Install dev tools from Aptitude
  environment:
    DEBIAN_FRONTEND: noninteractive
  sudo: true
  apt: name={{ item }} state=installed
  with_items:
   - bash-completion # Not included in the docker image
   - bzr
   - build-essential
   - cgdb
   - cmake
   - ctags
   - gdb
   - git
   - libssl-dev
   - jq
   - make
   - man-db
   - mercurial
   - mr
   - neovim
   - tig
   - vcsh

- name: Python support for neovim
  pip: name=neovim
  sudo: true

- name: Add docker gnupg key
  sudo: true
  command: "curl -sSL https://get.docker.com/gpg | sudo apt-key add -"

- name: Install docker
  sudo: true
  command:  "curl -sSL https://get.docker.com/ | sh"
