---

- name: Install system tools from Aptitude
  environment:
    DEBIAN_FRONTEND: noninteractive
  sudo: true
  apt: name={{ item }} state=installed
  with_items:
   - curl
   - dstat
   - dnsutils
   - htop
   - iotop
   - lynx
   - man-db
   - mtr
   - multitail
   - ngrep
   - silversearcher-ag
   - tmux
   - tree
   - vim
   - wget
   - zsh
